[package]
name = "wordcount"
version = "0.1.0"
authors = ["bx3 <71761807+scale-chain-sub@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tiny_http = "0.6"
rustc-serialize = "0.3"
