apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-deployment
spec:
  selector:
    matchLabels:
      app: wordcount 
  replicas: 1 
  template:
    metadata:
      labels:
        app: wordcount 
    spec:
      containers:
      - name: wordcount-app
        image: wordcount-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: wordcount
  labels:
    run: wordcount
spec:
  ports:
  - port: 40000 
    protocol: TCP
  selector:
    run: wordcount-deployment 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deployment
spec:
  selector:
    matchLabels:
      app: reverse 
  replicas: 1 
  template:
    metadata:
      labels:
        app: reverse 
    spec:
      containers:
      - name: reverse-app 
        image: reverse-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: reverse 
  labels:
    run: reverse 
spec:
  ports:
  - port: 40000
    protocol: TCP
  selector:
    run: reverse-deployment 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deployment
spec:
  selector:
    matchLabels:
      app: ingress 
  replicas: 1 
  template:
    metadata:
      labels:
        app: ingress 
    spec:
      containers:
      - name: ingress-app 
        image: ingress-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: ingress 
  labels:
    run: ingress 
spec:
  ports:
  - port: 40000
    protocol: TCP
  selector:
    run: ingress-deployment 

