apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-deployment
  labels:
    app: ingress
spec:
  selector:
    matchLabels:
      app: ingress 
  replicas: 1 
  template:
    metadata:
      labels:
        app: ingress 
    spec:
      containers:
      - name: ingress-container 
        image: ingress-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-service
spec:
  type: NodePort 
  selector:
    app: ingress 
  ports:
  - protocol: TCP
    port: 40000
    targetPort: 40000
    nodePort: 31000
  

