apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deployment
spec:
  selector:
    matchLabels:
      app: reverse 
  replicas: 1 
  template:
    metadata:
      labels:
        app: reverse 
    spec:
      containers:
      - name: reverse-app 
        image: reverse-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: reverse 
  labels:
    run: reverse 
spec:
  ports:
  - port: 40000
    protocol: TCP
  selector:
    run: reverse-deployment
