apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-deployment
spec:
  selector:
    matchLabels:
      app: wordcount 
  replicas: 1 
  template:
    metadata:
      labels:
        app: wordcount 
    spec:
      containers:
      - name: wordcount-app
        image: wordcount-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
