apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount-deployment
  labels:
    app: wordcount
spec:
  selector:
    matchLabels:
      app: wordcount 
  replicas: 1 
  template:
    metadata:
      labels:
        app: wordcount 
    spec:
      containers:
      - name: wordcount-app
        image: wordcount-app
        imagePullPolicy: Never
        ports:
        - containerPort: 40000 
---
apiVersion: v1
kind: Service
metadata:
  name: wordcount-service
spec:
  type: NodePort 
  ports:
  - protocol: TCP
    port: 40000 
    targetPort: 40000 
    nodePort: 32000
  selector:
    app: wordcount 
