apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-deploy
spec:
  selector:
    matchLabels:
      app: reverse 
  replicas: 1 
  template:
    metadata:
      labels:
        app: reverse 
    spec:
      containers:
      - name: reverse-app 
        image: bx33/reverse-app
        imagePullPolicy: IfNotPresent 
